sudo: required
dist: trusty
language: node_js
node_js:
  - "stable"
before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
  - sudo apt-get install -y geth
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build