sudo: required
dist: xenial
language: node_js
node_js:
  - "10"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update -qq
  - sudo apt-get install geth -y -qq
addons:
  snaps:
    - ipfs
env:
  - PATH=/snap/bin:$PATH
before_cache:
  - ipfs init
script:
  - npm test
before_deploy:  
  - npm run build
cache: 
  directories:
  - .embark  
  - /home/travis/.ipfs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  local_dir: dist
  keep_history: true
  on:
    branch: master