sudo: required
dist: xenial
language: node_js
node_js:
  - "10"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update -qq
  - sudo apt-get install geth -y -qq
addons:
  snaps:
    - ipfs
env:
  - PATH=/snap/bin:$PATH
cache:
  directories:
  - node_modules
before_script:
  - ipfs init
script:
  - npm test
  - npm run build