sudo: required
dist: xenial
language: node_js
node_js:
  - "10"
addons:
  snaps:
    - name: geth
      channel: candidate/latest
    - name: ipfs
      channel: stable/latest
env:
  - PATH=/snap/bin:$PATH
cache:
  directories:
  - node_modules
before_script:
  - ipfs init
script:
  - npm test
  - npm run build