sudo: required
dist: trusty
language: node_js
node_js:
  - "10"
addons:
  snaps:
    - geth
    - ipfs
cache:
  directories:
  - node_modules
before_script:
  - PATH=$PATH:/snap/bin
  - ipfs init
script:
  - npm test
  - npm run build