sudo: required
dist: xenial
language: node_js
node_js:
  - "10.17.0"
addons:
  snaps:
    - ipfs
env:
  - PATH=/snap/bin:$PATH
before_install:
  - ipfs init
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update -qq
  - sudo apt-get install geth -y -qq
  - < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32} > .password
cache: npm
script:
  - geth version
  - ipfs --version
  - npx embark --version
  - | 
    npx embark blockchain travis > blockchain.log &
    GETH_PID=$!  
  - | 
    ipfs daemon > storage.log &
    IPFS_PID=$!
  - npm test
before_deploy:
  - sleep 5
  - bash -c "SYNCED=0; echo \"Waiting for light sync\"; while [ $SYNCED -eq 0 ] ;  do      tail -n 3 blockchain.log;      sleep 10;      SYNCED=`geth attach /tmp/embark-*/geth.ipc --exec \"eth.blockNumber != 0 && eth.syncing === false ? 1 : 0\"`;  done"
  - npm run travis
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  local_dir: dist
  keep_history: true
  on:
    branch: master
after_script:
  - kill $GETH_PID
  - kill $IPFS_PID
  - npm run reset
  - cat blockchain.log
  - cat storage.log
  - rm .password
  - rm blockchain.log
  - rm storage.log