sudo: required
dist: trusty
language: node_js
node_js:
  - "10"
before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update -q
  - sudo apt-get install -y geth build-essential
addons:
  apt:
    update: true
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build