sudo: required
dist: xenial
language: node_js
node_js:
  - "10.17.0"
addons:
  snaps:
    - ipfs
env:
  - PATH=/snap/bin:$PATH
before_install:
  - ipfs init
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update -qq
  - sudo apt-get install geth -y -qq
  - < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32} > .password
cache: npm
script:
  - geth version
  - ipfs --version
  - npx embark --version
  - | 
    travis_wait npx embark blockchain travis
    GETH_PID=$!  
  - | 
    travis_wait ipfs daemon
    IPFS_PID=$!
  - sleep 60
  - npm test
before_deploy:
  - npm run travis
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  local_dir: dist
  keep_history: true
  on:
    branch: master
after_deploy: 
  - npm run reset
after_script:
  - kill $GETH_PID
  - kill $IPFS_PID
  - rm .password